### ISSUE TITLE
Add legal and privacy statement

### ISSUE THREAD

**Issue by thisismydesign** [Kexort/relic-checklist#42]
Unfortunately we do have a cookie coming from poecdn, otherwise we might wouldn't need a privacy statement. Needs investigation.

Legal statement:
> Path of Exile content and materials are trademarks and copyrights of Grinding Gear Games or its licensors.
> This site is fan-made and not affiliated with Grinding Gear Games in any way.

**Comment by thisismydesign** [comment]
![image](https://user-images.githubusercontent.com/3299948/45891804-c7ea5e80-bdc6-11e8-87b5-351d16061475.png)

![image](https://user-images.githubusercontent.com/3299948/45891819-cf116c80-bdc6-11e8-9cd1-11d450c95d2c.png)

**Comment by Kexort** [comment]
Why this Issue not closed automatically by merging #57?
